# Site settings
title: tnotm
email: john.thomas.oliphant@gmail.com
description: "John Oliphant"
baseurl: "/"
url: "http://tnotm.github.io"
twitter_username: tnotm
github_username: tnotm
disqus_username: tnotm
isso_domain: comments.mysite.org

# Build settings
markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
