# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: tnotm

description: John Oliphant
disqus: tnotm
author:
  name: John Oliphant
  photo: tnotm_avatar #base name of image, see readme
  email: 
  github: https://github.com/tnotm  #full profile URLs, see readme
  google_plus: https://plus.google.com/+JohnOliphant
  twitter: https://twitter.com/tnotm
  facebook: 
  pinterest: 
  linkedin: https://www.linkedin.com/in/johnoliphant
  bio: John Oliphant
  email_md5: 445495948ce984e411ee7de24c409f21

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 